### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by tobiasstraub** [turngeek/JavaEEinaDay_My-Memo-Servlet#1]
By starting the container within Codenvy, it caused in "Out of memory" error by starting wildfly server. By increasing the RAM in config file from one to two gigabytes, it works correctly.

**Comment by marcusschiesser** [comment]
HI @tobiasstraub: Thanks for the patch - just merged it - if it fixes your problem, please close the issue

**Comment by tobiasstraub** [comment]
Thanks, @marcusschiesser, this fixes the error for a lot of people here, inclusive me.
